### ISSUE TITLE
Include deleting a key (and it's value) as a learning objective.

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/ruby-hash#1]
See ga-wdi-boston/ruby-vs-js-hash-dictionary#13

**Comment by neugierige** [comment]
I think we can close this now that `.delete` has been added to the demo: https://github.com/ga-wdi-boston/ruby-hashes/blob/015/master/README.md

**Comment by gaand** [comment]
ga-wdi-boston/ruby-vs-js-hash-dictionary#13
