### ISSUE TITLE
Incorrect code in example for merging hash

### ISSUE THREAD

**Issue by jordanallain** [ga-wdi-boston/ruby-hash#13]
Edited to reflect Antony's comment:

```diff
 > apartment.merge({rent: 1000})
-=> {:street=>"255 Long Road", :city=>"Awesomeville", :bedrooms=>3, :rent=>1000}
+=> {:address=>{:street=>"255 Long Road", :city=>"Awesomeville", :bedrooms=>3}, :rent=>1000}
```

**Comment by gaand** [comment]
Correct the output, please.  That seems a semantically superior solution.

Also, your diff doesn't seem to match the README.md in terms of what's displayed.

**Comment by jordanallain** [comment]
Fixed original diff 


Also this is incorrect

```rb
  apartment.keys
=> [:address, :city, :bedrooms, :occupants, :rent]
```

as `:city` and `:bedrooms` are keys to `apartment[:address]`

**Comment by jordanallain** [comment]
And at the risk of sounding pedantic maybe we should move `:bedrooms` outside of `apartment[:address]` to simply be a part of `apartment`. Or remove `:bedrooms` entirely?

**Comment by gaand** [comment]
It won't if your diff is formatted correctly.  All unchanged lines start with a space.

Agreed that it's incorrect.  

Good catch on where bedrooms are stored.  Please, be pedantic.  Move it out of `address`.

**Comment by jordanallain** [comment]
Last thing on this but when we merge `apartment` hash with `{ rent: 1000 }` we aren't including the `!` after `merge` to mutate `apartment`, but later in the talk we are trying to access and mutate `apartment[:rent]` so I think we need to include the `!` for that to work.

**Comment by gaand** [comment]
Please avoid mutating objects (`!`).  Prefer storing new object.
