### ISSUE TITLE
Rename to ruby-hash

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/ruby-hash#4]
I believe that conforms more closely to our naming conventions.

**Comment by MicFin** [comment]
Can this be closed?  The repo was re-named to ruby-hash with issue #7.

**Comment by BenGitsCode** [comment]
This still needs to be addressed, #7 was never merged. I'll close that PR now and reference this, but this issue should remain open until the diff in #7 is merged to master.

**Comment by payne-chris-r** [comment]
Ok to close.
